dbt-postgres:
  target: dev
  outputs:
    dev:
      type: postgres
      host: 127.0.0.1
      user: username
      password: password
      port: 5432
      dbname: dbt_db
      schema: dbt_schema
      threads: 2
      keepalives_idle: 0 # default 0, indicating the system default. See below
      connect_timeout: 10 # default 10 seconds
      retries: 1  # default 1 retry on error/timeout when opening connections